//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Docimax.Data_ICD.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseDic_ICD_Diagnosis_Log
    {
        public int ICDDiagnosisLogID { get; set; }
        public Nullable<int> ICDID { get; set; }
        public string OperateTagert { get; set; }
        public Nullable<int> OperateType { get; set; }
        public Nullable<System.DateTime> OperateTime { get; set; }
        public string OperateUserID { get; set; }
        public string OperateIP { get; set; }
        public string OperateUserName { get; set; }
        public string OperateHospitalName { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
        public string LastModifyUserID { get; set; }
    }
}
