//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Docimax.Data_ICD.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseDic_Code_History
    {
        public int CodeHistoryID { get; set; }
        public string CodeNum { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
    }
}
