//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Docimax.Data_ICD.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Code_Order_Operate
    {
        public int CodeOrderOperateID { get; set; }
        public Nullable<int> CodeOrderID { get; set; }
        public string ICDCode { get; set; }
        public string ICDContent { get; set; }
        public Nullable<System.DateTime> OperateTime { get; set; }
        public string OperateLevel { get; set; }
        public string Opetator { get; set; }
        public string Assistant1 { get; set; }
        public string Assistant2 { get; set; }
        public string Anesthesia { get; set; }
        public string Anesthesiologist { get; set; }
        public Nullable<int> OperateIndex { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUserID { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
        public string LastModifyUserID { get; set; }
        public Nullable<int> DeleteFlag { get; set; }
        public byte[] LastModifyStamp { get; set; }
        public string ClinicalOperate { get; set; }
    }
}
