//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Docimax.Data_ICD.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Interface
    {
        public long RequestID { get; set; }
        public string AuthCode { get; set; }
        public string TicketID { get; set; }
        public Nullable<int> CodeOrderID { get; set; }
        public string Version { get; set; }
        public Nullable<System.DateTime> RequestTime { get; set; }
        public Nullable<System.DateTime> GetRequestTime { get; set; }
        public string RequestIp { get; set; }
        public string InterfaceName { get; set; }
        public string SyncResponseCode { get; set; }
        public string SyncResponseStr { get; set; }
        public Nullable<System.DateTime> SyncResponseTime { get; set; }
        public string NotifyCode { get; set; }
        public string NotiryStr { get; set; }
        public string NotifyContent { get; set; }
    }
}
