//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Docimax.Data_ICD.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORG_Service_Assign
    {
        public int ORG_Service_AssignedID { get; set; }
        public Nullable<int> ORG_ServiceID { get; set; }
        public string UserID { get; set; }
        public Nullable<bool> Enable { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUserID { get; set; }
        public Nullable<System.DateTime> LastModtifyTime { get; set; }
        public string LastModityUserID { get; set; }
        public byte[] LastModifyStamp { get; set; }
        public Nullable<int> ORG_ID { get; set; }
    }
}
