//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Docimax.Data_ICD.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_ChangeAuditLog
    {
        public int UserChangeID { get; set; }
        public string UserID { get; set; }
        public string OriginValue { get; set; }
        public string NewValue { get; set; }
        public Nullable<int> OperateTarget { get; set; }
        public string OperateUserID { get; set; }
        public Nullable<System.DateTime> Operatedatetime { get; set; }
        public Nullable<int> OperateType { get; set; }
        public string OpertateDescription { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> DeleteFlag { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
