//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Docimax.Data_ICD.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebChat_User
    {
        public string Openid { get; set; }
        public string Unionid { get; set; }
        public string Appid { get; set; }
        public string UserID { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string NikceName { get; set; }
        public Nullable<int> Gender { get; set; }
        public string AvatarUrl { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
    }
}
