//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Docimax.Data_ICD.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebChat_UserSearchLog
    {
        public string LogID { get; set; }
        public string Openid { get; set; }
        public string SearchFilter { get; set; }
        public Nullable<System.DateTime> SearchTime { get; set; }
        public Nullable<int> ICDVersionID { get; set; }
        public Nullable<int> ICDVersionType { get; set; }
        public string SegmentResult { get; set; }
    }
}
